name: Vädret Android App

on:
  pull_request:
    push:
      branches:
        - dev
        - master

jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup project
        run: |
          - echo "{{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run ktlint
        run: ./gradlew ktlint
  tests:
    name: unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Tests
        run: ./gradlew test